const VIDASOCIAL_COLLECTION = '@VidaSocial';
const RELACIONAMENTO_COLLECTION = '@Relacionamento';
const PESSOAL_COLLECTION = '@Pessoal';
const PROFISSIONAL_COLLECTION = '@Profissional';
const QUALIDADEVIDA_COLLECTION = '@QualidadeDeVida';

export { VIDASOCIAL_COLLECTION, RELACIONAMENTO_COLLECTION, PESSOAL_COLLECTION, PROFISSIONAL_COLLECTION, QUALIDADEVIDA_COLLECTION }